
import { ClipboardList, Globe, ReceiptText, ScrollText, Settings, Truck, User, UsersRound } from "lucide-react";
import sonangol from "@/img/sonangol.png"
import chevron from "@/img/chevron.png"
import total from "@/img/totaljpg.jpg"

export const menu =[
    {id:1, title:"Gestão de Clientes", icon: UsersRound, href:"/dashboard/gestao-clientes"},
    {id:2, title:"Gestão de Requisições", icon: ReceiptText, href:"/dashboard/gestao-requisicoes"},
    {id:3, title:"Gestão de Fornecedores", icon: Truck, href:"/dashboard/gestao-fornecedores"},
    {id:3, title:"Sourcing", icon: Globe, href:"/dashboard/sourcing"},
    {id:4, title:"Pró-formas", icon: ScrollText, href:"/dashboard"},
    {id:5, title:"Gestão de Facturas", icon: ClipboardList, href:"/dashboard"},
    {id:6, title:"Gestão de Prudutos", icon: ClipboardList, href:"/dashboard"},
]
export const settings =[
    {id:1, title:"Perfil", icon: User, href:"/dashboard/gestao-clientes"},
    {id:2, title:"Definições", icon: Settings, href:"/dashboard/gestao-requisicoes"},
]

export const tipoCliente = [
    { id: 1, title: "Normal" },
    { id: 1, title: "Auto Faturação" },
    
  ];
  
export const ivaCativo = [
    { id: 1, title: "Sim" },
    { id: 1, title: "Não" },
    
  ];

  export const paisesDoMundo = [
    { id: 1, title: "Afeganistão" },
    { id: 2, title: "África do Sul" },
    { id: 3, title: "Albânia" },
    { id: 4, title: "Alemanha" },
    { id: 5, title: "Andorra" },
    { id: 6, title: "Angola" },
    { id: 7, title: "Antígua e Barbuda" },
    { id: 8, title: "Arábia Saudita" },
    { id: 9, title: "Argélia" },
    { id: 10, title: "Argentina" },
    { id: 11, title: "Armênia" },
    { id: 12, title: "Austrália" },
    { id: 13, title: "Áustria" },
    { id: 14, title: "Azerbaijão" },
    { id: 15, title: "Bahamas" },
    { id: 16, title: "Bangladesh" },
    { id: 17, title: "Barbados" },
    { id: 18, title: "Bahrein" },
    { id: 19, title: "Belarus" },
    { id: 20, title: "Bélgica" },
    { id: 21, title: "Belize" },
    { id: 22, title: "Benin" },
    { id: 23, title: "Bolívia" },
    { id: 24, title: "Bósnia e Herzegovina" },
    { id: 25, title: "Botsuana" },
    { id: 26, title: "Brasil" },
    { id: 27, title: "Brunei" },
    { id: 28, title: "Bulgária" },
    { id: 29, title: "Burquina Faso" },
    { id: 30, title: "Burundi" },
    { id: 31, title: "Butão" },
    { id: 32, title: "Cabo Verde" },
    { id: 33, title: "Camarões" },
    { id: 34, title: "Camboja" },
    { id: 35, title: "Canadá" },
    { id: 36, title: "Catar" },
    { id: 37, title: "Cazaquistão" },
    { id: 38, title: "Chade" },
    { id: 39, title: "Chile" },
    { id: 40, title: "China" },
    { id: 41, title: "Chipre" },
    { id: 42, title: "Colômbia" },
    { id: 43, title: "Comores" },
    { id: 44, title: "Congo" },
    { id: 45, title: "Coreia do Norte" },
    { id: 46, title: "Coreia do Sul" },
    { id: 47, title: "Costa do Marfim" },
    { id: 48, title: "Costa Rica" },
    { id: 49, title: "Croácia" },
    { id: 50, title: "Cuba" },
    { id: 51, title: "Dinamarca" },
    { id: 52, title: "Djibouti" },
    { id: 53, title: "Dominica" },
    { id: 54, title: "Egito" },
    { id: 55, title: "El Salvador" },
    { id: 56, title: "Emirados Árabes Unidos" },
    { id: 57, title: "Equador" },
    { id: 58, title: "Eritreia" },
    { id: 59, title: "Eslováquia" },
    { id: 60, title: "Eslovênia" },
    { id: 61, title: "Espanha" },
    { id: 62, title: "Estados Unidos" },
    { id: 63, title: "Estônia" },
    { id: 64, title: "Eswatini" },
    { id: 65, title: "Etiópia" },
    { id: 66, title: "Fiji" },
    { id: 67, title: "Filipinas" },
    { id: 68, title: "Finlândia" },
    { id: 69, title: "França" },
    { id: 70, title: "Gabão" },
    { id: 71, title: "Gâmbia" },
    { id: 72, title: "Gana" },
    { id: 73, title: "Geórgia" },
    { id: 74, title: "Granada" },
    { id: 75, title: "Grécia" },
    { id: 76, title: "Guatemala" },
    { id: 77, title: "Guiana" },
    { id: 78, title: "Guiné" },
    { id: 79, title: "Guiné-Bissau" },
    { id: 80, title: "Guiné Equatorial" },
    { id: 81, title: "Haiti" },
    { id: 82, title: "Holanda" },
    { id: 83, title: "Honduras" },
    { id: 84, title: "Hungria" },
    { id: 85, title: "Iêmen" },
    { id: 86, title: "Ilhas Marshall" },
    { id: 87, title: "Ilhas Salomão" },
    { id: 88, title: "Índia" },
    { id: 89, title: "Indonésia" },
    { id: 90, title: "Irã" },
    { id: 91, title: "Iraque" },
    { id: 92, title: "Irlanda" },
    { id: 93, title: "Islândia" },
    { id: 94, title: "Israel" },
    { id: 95, title: "Itália" },
    { id: 96, title: "Jamaica" },
    { id: 97, title: "Japão" },
    { id: 98, title: "Jordânia" },
    { id: 99, title: "Kiribati" },
    { id: 100, title: "Kuwait" },
    { id: 101, title: "Laos" },
    { id: 102, title: "Lesoto" },
    { id: 103, title: "Letônia" },
    { id: 104, title: "Líbano" },
    { id: 105, title: "Libéria" },
    { id: 106, title: "Líbia" },
    { id: 107, title: "Liechtenstein" },
    { id: 108, title: "Lituânia" },
    { id: 109, title: "Luxemburgo" },
    { id: 110, title: "Madagascar" },
    { id: 111, title: "Malásia" },
    { id: 112, title: "Malaui" },
    { id: 113, title: "Maldivas" },
    { id: 114, title: "Mali" },
    { id: 115, title: "Malta" },
    { id: 116, title: "Marrocos" },
    { id: 117, title: "Maurício" },
    { id: 118, title: "México" },
    { id: 119, title: "Mônaco" },
    { id: 120, title: "Mongólia" },
    { id: 121, title: "Nepal" },
    { id: 122, title: "Nicarágua" },
    { id: 123, title: "Nigéria" },
    { id: 124, title: "Noruega" },
    { id: 125, title: "Nova Zelândia" },
    { id: 126, title: "Paraguai" },
    { id: 127, title: "Peru" },
    { id: 128, title: "Portugal" },
    { id: 129, title: "Reino Unido" },
    { id: 130, title: "Uruguai" },
    { id: 131, title: "Venezuela" },
  ];
  
  
  
  

  export const provinciasDeAngola = [
    { id: 1, title: "Bengo" },
    { id: 2, title: "Benguela" },
    { id: 3, title: "Bié" },
    { id: 4, title: "Cabinda" },
    { id: 5, title: "Cuando Cubango" },
    { id: 6, title: "Cuanza Norte" },
    { id: 7, title: "Cuanza Sul" },
    { id: 8, title: "Cunene" },
    { id: 9, title: "Huambo" },
    { id: 10, title: "Huíla" },
    { id: 11, title: "Lunda Norte" },
    { id: 12, title: "Lunda Sul" },
    { id: 13, title: "Luanda" },
    { id: 14, title: "Malanje" },
    { id: 15, title: "Moxico" },
    { id: 16, title: "Namibe" },
    { id: 17, title: "Uíge" },
    { id: 18, title: "Zaire" },
  ];
  
 
  

  
  export const clientes = [
    { nomeCliente: "CHEVRON", cidade: "Luanda", contribuinte: "512345678", email: "joao.silva@chevron.com", endereco: "Rua 1, Bairro Azul", telefone: "+244 923456789", site: "www.joaosilva.com", imagem: chevron },
    { nomeCliente: "TOTAL", cidade: "Benguela", contribuinte: "612345679", email: "maria.fernandes@total.com", endereco: "Avenida Central, 45", telefone: "+244 923456788", site: "www.mariaf.com", imagem: total},
    { nomeCliente: "SONANGOL", cidade: "Huambo", contribuinte: "712345670", email: "pedro.santos@sonangol.com", endereco: "Rua das Acácias, 12", telefone: "+244 923456787", site: "www.pedrosantos.com", imagem: sonangol },
    
  ];
  